#############################################################################
# Makefile for building: rinf-gui
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  rinf-gui.pro
# Template: app
# Command: /usr/local/qt5/bin/qmake -o Makefile rinf-gui.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Qt-5.5.1/include -I/usr/local/Qt-5.5.1/include/QtWidgets -I/usr/local/Qt-5.5.1/include/QtGui -I/usr/local/Qt-5.5.1/include/QtCore -I. -I/usr/local/Qt-5.5.1/mkspecs/linux-g++
QMAKE         = /usr/local/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = rinf-gui1.0.0
DISTDIR = /home/pi/dev/rinf-gui/.tmp/rinf-gui1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.5.1/lib
LIBS          = $(SUBLIBS) -lgps -lasound -L/usr/local/Qt-5.5.1/lib -lQt5Widgets -lQt5Gui -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gps-func.cpp \
		soundnotify.cpp \
		soundplay.cpp \
		logger.cpp \
		pixmaker.cpp qrc_graph.cpp \
		moc_mainwindow.cpp \
		moc_soundnotify.cpp \
		moc_soundplay.cpp \
		moc_logger.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gps-func.o \
		soundnotify.o \
		soundplay.o \
		logger.o \
		pixmaker.o \
		qrc_graph.o \
		moc_mainwindow.o \
		moc_soundnotify.o \
		moc_soundplay.o \
		moc_logger.o
DIST          = /usr/local/Qt-5.5.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/lex.prf \
		rinf-gui.pro mainwindow.h \
		gps-func.h \
		radarobjects.h \
		soundnotify.h \
		soundplay.h \
		logger.h \
		pixmaker.h main.cpp \
		mainwindow.cpp \
		gps-func.cpp \
		soundnotify.cpp \
		soundplay.cpp \
		logger.cpp \
		pixmaker.cpp
QMAKE_TARGET  = rinf-gui
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = rinf-gui


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rinf-gui.pro /usr/local/Qt-5.5.1/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.5.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5.1/mkspecs/features/lex.prf \
		rinf-gui.pro \
		graph.qrc \
		/usr/local/Qt-5.5.1/lib/libQt5Widgets.prl \
		/usr/local/Qt-5.5.1/lib/libQt5Gui.prl \
		/usr/local/Qt-5.5.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile rinf-gui.pro
/usr/local/Qt-5.5.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.5.1/mkspecs/common/unix.conf:
/usr/local/Qt-5.5.1/mkspecs/common/linux.conf:
/usr/local/Qt-5.5.1/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.5.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.5.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.5.1/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.5.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.5.1/mkspecs/qconfig.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.5.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.5.1/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.5.1/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.5.1/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.5.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.5.1/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.5.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.5.1/mkspecs/features/default_post.prf:
/usr/local/Qt-5.5.1/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.5.1/mkspecs/features/qt.prf:
/usr/local/Qt-5.5.1/mkspecs/features/resources.prf:
/usr/local/Qt-5.5.1/mkspecs/features/moc.prf:
/usr/local/Qt-5.5.1/mkspecs/features/uic.prf:
/usr/local/Qt-5.5.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.5.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.5.1/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.5.1/mkspecs/features/yacc.prf:
/usr/local/Qt-5.5.1/mkspecs/features/lex.prf:
rinf-gui.pro:
graph.qrc:
/usr/local/Qt-5.5.1/lib/libQt5Widgets.prl:
/usr/local/Qt-5.5.1/lib/libQt5Gui.prl:
/usr/local/Qt-5.5.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile rinf-gui.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents graph.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h gps-func.h radarobjects.h soundnotify.h soundplay.h logger.h pixmaker.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp gps-func.cpp soundnotify.cpp soundplay.cpp logger.cpp pixmaker.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_graph.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_graph.cpp
qrc_graph.cpp: graph.qrc \
		img/zoom.png \
		img/red-led.png \
		img/track-recordin.png \
		img/no-speed-notify.png \
		img/gps-off.png \
		img/yellow1-led.png \
		img/gps-on.png \
		img/yellow-led.png \
		img/no-cam-notify.png \
		img/old/pathing.png \
		img/green-led.png
	/usr/local/Qt-5.5.1/bin/rcc -name graph graph.qrc -o qrc_graph.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_soundnotify.cpp moc_soundplay.cpp moc_logger.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_soundnotify.cpp moc_soundplay.cpp moc_logger.cpp
moc_mainwindow.cpp: /usr/local/Qt-5.5.1/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qicon.h \
		/usr/local/Qt-5.5.1/include/QtCore/QList \
		/usr/local/Qt-5.5.1/include/QtCore/QTimer \
		/usr/local/Qt-5.5.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFile \
		/usr/local/Qt-5.5.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.5.1/include/QtGui/QKeyEvent \
		/usr/local/Qt-5.5.1/include/QtGui/QImage \
		gps-func.h \
		/usr/local/Qt-5.5.1/include/QtCore/QString \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		radarobjects.h \
		soundnotify.h \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		soundplay.h \
		pixmaker.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFont \
		/usr/local/Qt-5.5.1/include/QtGui/QFontMetrics \
		/usr/local/Qt-5.5.1/include/QtGui/QPainter \
		/usr/local/Qt-5.5.1/include/QtGui/qpainter.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpen.h \
		/usr/local/Qt-5.5.1/include/QtCore/QRect \
		/usr/local/Qt-5.5.1/include/QtGui/QPixmap \
		/usr/local/Qt-5.5.1/include/QtCore/QDebug \
		mainwindow.h
	/usr/local/Qt-5.5.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.5.1/mkspecs/linux-g++ -I/home/pi/dev/rinf-gui -I/usr/local/Qt-5.5.1/include -I/usr/local/Qt-5.5.1/include/QtWidgets -I/usr/local/Qt-5.5.1/include/QtGui -I/usr/local/Qt-5.5.1/include/QtCore -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/arm-linux-gnueabihf -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_soundnotify.cpp: /usr/local/Qt-5.5.1/include/QtCore/QString \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		soundplay.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		soundnotify.h
	/usr/local/Qt-5.5.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.5.1/mkspecs/linux-g++ -I/home/pi/dev/rinf-gui -I/usr/local/Qt-5.5.1/include -I/usr/local/Qt-5.5.1/include/QtWidgets -I/usr/local/Qt-5.5.1/include/QtGui -I/usr/local/Qt-5.5.1/include/QtCore -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/arm-linux-gnueabihf -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include soundnotify.h -o moc_soundnotify.cpp

moc_soundplay.cpp: /usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		soundplay.h
	/usr/local/Qt-5.5.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.5.1/mkspecs/linux-g++ -I/home/pi/dev/rinf-gui -I/usr/local/Qt-5.5.1/include -I/usr/local/Qt-5.5.1/include/QtWidgets -I/usr/local/Qt-5.5.1/include/QtGui -I/usr/local/Qt-5.5.1/include/QtCore -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/arm-linux-gnueabihf -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include soundplay.h -o moc_soundplay.cpp

moc_logger.cpp: /usr/local/Qt-5.5.1/include/QtCore/QCoreApplication \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtCore/QtDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/QtGlobal \
		logger.h
	/usr/local/Qt-5.5.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.5.1/mkspecs/linux-g++ -I/home/pi/dev/rinf-gui -I/usr/local/Qt-5.5.1/include -I/usr/local/Qt-5.5.1/include/QtWidgets -I/usr/local/Qt-5.5.1/include/QtGui -I/usr/local/Qt-5.5.1/include/QtCore -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/arm-linux-gnueabihf -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include logger.h -o moc_logger.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		/usr/local/Qt-5.5.1/include/QtCore/QtGlobal \
		/usr/local/Qt-5.5.1/include/QtWidgets/QDesktopWidget \
		/usr/local/Qt-5.5.1/include/QtCore/QtMessageHandler \
		/usr/local/Qt-5.5.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.5.1/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDebug \
		mainwindow.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qicon.h \
		/usr/local/Qt-5.5.1/include/QtCore/QList \
		/usr/local/Qt-5.5.1/include/QtCore/QTimer \
		/usr/local/Qt-5.5.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFile \
		/usr/local/Qt-5.5.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.5.1/include/QtGui/QKeyEvent \
		/usr/local/Qt-5.5.1/include/QtGui/QImage \
		gps-func.h \
		/usr/local/Qt-5.5.1/include/QtCore/QString \
		radarobjects.h \
		soundnotify.h \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		soundplay.h \
		pixmaker.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFont \
		/usr/local/Qt-5.5.1/include/QtGui/QFontMetrics \
		/usr/local/Qt-5.5.1/include/QtGui/QPainter \
		/usr/local/Qt-5.5.1/include/QtGui/qpainter.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpen.h \
		/usr/local/Qt-5.5.1/include/QtCore/QRect \
		/usr/local/Qt-5.5.1/include/QtGui/QPixmap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /usr/local/Qt-5.5.1/include/QtGui/QPainter \
		/usr/local/Qt-5.5.1/include/QtGui/qpainter.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpen.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtCore/QRect \
		/usr/local/Qt-5.5.1/include/QtGui/QPen \
		/usr/local/Qt-5.5.1/include/QtGui/QBrush \
		/usr/local/Qt-5.5.1/include/QtCore/QList \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFontMetrics \
		/usr/local/Qt-5.5.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.5.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.5.1/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.5.1/include/QtCore/QTextCodec \
		/usr/local/Qt-5.5.1/include/QtCore/qtextcodec.h \
		/usr/local/Qt-5.5.1/include/QtGui/QKeyEvent \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDebug \
		/usr/local/Qt-5.5.1/include/QtCore/QSettings \
		/usr/local/Qt-5.5.1/include/QtCore/qsettings.h \
		/usr/local/Qt-5.5.1/include/QtCore/QTimer \
		/usr/local/Qt-5.5.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFileInfoList \
		mainwindow.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qicon.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFile \
		/usr/local/Qt-5.5.1/include/QtGui/QImage \
		gps-func.h \
		/usr/local/Qt-5.5.1/include/QtCore/QString \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		radarobjects.h \
		soundnotify.h \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		soundplay.h \
		pixmaker.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFont \
		/usr/local/Qt-5.5.1/include/QtGui/QPixmap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gps-func.o: gps-func.cpp /usr/local/Qt-5.5.1/include/QtCore/QDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.5.1/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.5.1/include/QtCore/QObject \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		gpsmath.h \
		gps-func.h \
		/usr/local/Qt-5.5.1/include/QtCore/QString \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h \
		radarobjects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gps-func.o gps-func.cpp

soundnotify.o: soundnotify.cpp /usr/local/Qt-5.5.1/include/QtCore/QDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.5.1/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFile \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/QObject \
		soundnotify.h \
		/usr/local/Qt-5.5.1/include/QtCore/QString \
		/usr/local/Qt-5.5.1/include/QtCore/QThread \
		/usr/local/Qt-5.5.1/include/QtCore/qthread.h \
		soundplay.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundnotify.o soundnotify.cpp

soundplay.o: soundplay.cpp /usr/local/Qt-5.5.1/include/QtCore/QDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFile \
		/usr/local/Qt-5.5.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/QDir \
		/usr/local/Qt-5.5.1/include/QtCore/qdir.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/QTextCodec \
		/usr/local/Qt-5.5.1/include/QtCore/qtextcodec.h \
		/usr/local/Qt-5.5.1/include/QtCore/QFileInfo \
		soundplay.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5.1/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5.1/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundplay.o soundplay.cpp

logger.o: logger.cpp logger.h \
		/usr/local/Qt-5.5.1/include/QtCore/QCoreApplication \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5.1/include/QtCore/QtDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5.1/include/QtCore/QtGlobal
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

pixmaker.o: pixmaker.cpp pixmaker.h \
		/usr/local/Qt-5.5.1/include/QtGui/QImage \
		/usr/local/Qt-5.5.1/include/QtGui/qimage.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5.1/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.5.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5.1/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5.1/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.5.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.5.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5.1/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.5.1/include/QtCore/qline.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5.1/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFont \
		/usr/local/Qt-5.5.1/include/QtGui/qfont.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5.1/include/QtGui/QFontMetrics \
		/usr/local/Qt-5.5.1/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5.1/include/QtGui/QPainter \
		/usr/local/Qt-5.5.1/include/QtGui/qpainter.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5.1/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5.1/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5.1/include/QtGui/qpen.h \
		/usr/local/Qt-5.5.1/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5.1/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5.1/include/QtCore/QRect \
		/usr/local/Qt-5.5.1/include/QtGui/QPixmap \
		/usr/local/Qt-5.5.1/include/QtCore/QDebug \
		/usr/local/Qt-5.5.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.5.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5.1/include/QtCore/qset.h \
		/usr/local/Qt-5.5.1/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixmaker.o pixmaker.cpp

qrc_graph.o: qrc_graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_graph.o qrc_graph.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_soundnotify.o: moc_soundnotify.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundnotify.o moc_soundnotify.cpp

moc_soundplay.o: moc_soundplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundplay.o moc_soundplay.cpp

moc_logger.o: moc_logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logger.o moc_logger.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

